// Jest manual mock for fs-extra (ESM)
const fsExtra = {
  ensureDir: jest.fn(async () => {}),
  ensureDirSync: jest.fn(() => {}),
  ensureFile: jest.fn(async () => {}),
  ensureFileSync: jest.fn(() => {}),
  emptyDir: jest.fn(async () => {}),
  emptyDirSync: jest.fn(() => {}),
  readFile: jest.fn(async () => ''),
  readFileSync: jest.fn(() => ''),
  writeFile: jest.fn(async () => {}),
  writeFileSync: jest.fn(() => {}),
  outputFile: jest.fn(async () => {}),
  outputFileSync: jest.fn(() => {}),
  readJson: jest.fn(async () => ({})),
  readJsonSync: jest.fn(() => ({})),
  writeJson: jest.fn(async () => {}),
  writeJsonSync: jest.fn(() => {}),
  outputJson: jest.fn(async () => {}),
  outputJsonSync: jest.fn(() => {}),
  pathExists: jest.fn(async () => false),
  pathExistsSync: jest.fn(() => false),
  existsSync: jest.fn(() => false),
  mkdirSync: jest.fn(() => {}),
  readdir: jest.fn(async () => []),
  readdirSync: jest.fn(() => []),
  copy: jest.fn(async () => {}),
  copySync: jest.fn(() => {}),
  remove: jest.fn(async () => {}),
  removeSync: jest.fn(() => {}),
  rm: jest.fn(async () => {}),
  rmSync: jest.fn(() => {}),
  mkdirs: jest.fn(async () => {}),
  mkdtemp: jest.fn(async (prefix: string) => `${prefix}${Math.random().toString(16).slice(2, 8)}`),
  statSync: jest.fn(() => ({
    isDirectory: () => false,
    isFile: () => true,
    isSymbolicLink: () => false,
    size: 0,
  })),
  lstatSync: jest.fn(() => ({
    isSymbolicLink: () => false,
    isDirectory: () => false,
    isFile: () => true,
  })),
  symlink: jest.fn(async () => {}),
  createReadStream: jest.fn(),
  createWriteStream: jest.fn(),
};

export default fsExtra;
export const {
  ensureDir,
  ensureDirSync,
  ensureFile,
  ensureFileSync,
  emptyDir,
  emptyDirSync,
  readFile,
  readFileSync,
  writeFile,
  writeFileSync,
  outputFile,
  outputFileSync,
  readJson,
  readJsonSync,
  writeJson,
  writeJsonSync,
  outputJson,
  outputJsonSync,
  pathExists,
  pathExistsSync,
  existsSync,
  mkdirSync,
  readdir,
  readdirSync,
  copy,
  copySync,
  remove,
  removeSync,
  rm,
  mkdirs,
  mkdtemp,
  statSync,
  lstatSync,
  symlink,
  createReadStream,
  createWriteStream,
} = fsExtra;
